displayName: Request Logger(TEST)
type: middleware
iconPath: .assets/icon.png

import: github.com/FlowingSPDG/traefik-plugin-logger

summary: '[TEST] Log request'

testData:
  Prefix: [TEST LOG]
  LogLevel: info
